**Zadatak:**

Kreiraj dvije matrice formata $10\times5$ koje u svakom redu sadrže nasumične brojeve od 0 do 100. Pronaći gdje matrice A i B imaju maksimalne elemente vrsti na istim pozicijama, tj. u istoj koloni za istu vrstu. Pokušaj da ne koristiš petlje pri pronalsku pozicija.

In [ ]:
import numpy as np
from tensorflow.keras.utils import to_categorical

In [4]:
mat_a = (np.random.rand(10, 5) * 100).astype('int64')
mat_b = (np.random.rand(10, 5) * 100).astype('int64')

In [6]:
mat_a_max_per_row = to_categorical(np.argmax(mat_a, axis=1), 5)
mat_b_max_per_row = to_categorical(np.argmax(mat_b, axis=1), 5)

In [7]:
result = mat_a_max_per_row + mat_b_max_per_row
print(result)

[[0. 0. 0. 2. 0.]
 [0. 0. 1. 0. 1.]
 [0. 1. 1. 0. 0.]
 [0. 0. 1. 0. 1.]
 [1. 0. 0. 1. 0.]
 [2. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0.]
 [1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 2.]
 [0. 1. 1. 0. 0.]]


In [9]:
AB_max_per_row = np.where(result==2)
print(AB_max_per_row)

(array([0, 5, 8]), array([3, 0, 4]))


In [10]:
AB_max_per_row_pos = list(zip(AB_max_per_row[0], AB_max_per_row[1]))
print("pozicije:", AB_max_per_row_pos)

pozicije: [(0, 3), (5, 0), (8, 4)]
